### ISSUE TITLE
"code 404: No such image" when adding or updating AUR package

### ISSUE THREAD

**Issue by ralphocdol** [Lukas-Heiligenbrunner/AURCache#115]
I tried adding or even updating a package but the build fails with log:

```log
Pulling image: ghcr.io/lukas-heiligenbrunner/aurcache-builder:latest
Digest: sha256:a5aa452bb86f928efee5aa84f67e91044787f1695be0ce634c03683bd37dd1c2
Status: Image is up to date for ghcr.io/lukas-heiligenbrunner/aurcache-builder:latest
Docker responded with status code 404: No such image: latest:latest
```

The package in question is `mystiq` but its not limited to it, I think all package does this, I even tried adding `hyprgui-bin` and updating `firefox-pwa-bin` with the same error.

This is my compose file:
```yaml
version: "3"
services:
  aur-cache:
    container_name: aur-cache
    image: ghcr.io/lukas-heiligenbrunner/aurcache:latest
    network_mode: bridge
    ports:
      - 8180:8080
      - 8181:8081
    restart: always
    volumes:
      - ${VOL1}/extra/a:/home/podman/.local/share/containers
      - ${VOL2}/db:/app/db
      - ${VOL1}/extra/b:/var/lib/containers
      - ${VOL1}/repo:/app/repo
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOL1}/builds:/app/builds
    environment:
      - BUILD_ARTIFACT_DIR=${VOL1}/builds
```

this came from version `v0.1.5` to now `v0.2.0`, was there a breaking change?
I also tried using version `v0.1.5` to `git` before with same issue except I tried starting over (deleting `${VOL1}` and `${VOL2}` contents)

No helpful logs in the container
