### ISSUE TITLE
help: oauth redirect loop

### ISSUE THREAD

**Issue by schmoaaaaah** [Lukas-Heiligenbrunner/AURCache#164]
Hey.

I am trying to setup the oauth authentication with authentik but i get stuck with an: ERR_TOO_MANY_REDIRECTS.
The logs dont show anything about auth failures.
It does this in a loop:
```
aurcache.de/api/login --> authentik.de/application/o/authorize/ --> aurcache.de/oauth/callback
```

config:
```
  MAX_CONCURRENT_BUILDS: 1
  LOG_LEVEL: "DEBUG"
  DB_TYPE: POSTGRESQL
  DB_USER: aurcache
  DB_PWD: A_Passwort
  DB_HOST: postgres:5432
  DB_NAME: aurcache
  SECRET_KEY: A_Secret
  OAUTH_AUTH_URI: https://authentik.de/application/o/authorize/
  OAUTH_TOKEN_URI: https://authentik.de/application/o/token/
  OAUTH_USERINFO_URI: https://authentik.de/application/o/userinfo/
  OAUTH_CLIENT_ID: A_ID
  OAUTH_CLIENT_SECRET: A_SECRET
  OAUTH_REDIRECT_URI: https://aurcache.de/oauth/callback
```
version: `0.3.0`
reverse proxy: `traefik:v3`

I assume i am doing something wrong, but i am not sure what.
I might add that i am running it on k8s.

**Comment by Lukas-Heiligenbrunner** [comment]
My stack looks like this:

```
# id:671be574ec048ac220b73b92

x-base: &base
  extends:
    service: base
    file: common/base.yaml

services:
  aurcache:
    <<: *base
    image: ghcr.io/lukas-heiligenbrunner/aurcache:git@sha256:1f15ef9ffc6e08937eb653a271393215ab67b4e1741577f729d91bdd46c28755
    ports:
      - "9091:8080"
      - "9090:8081"
    volumes:
      - ${STORAGE_DATA_DIR}/aurcache/repo:/app/repo
    privileged: true
    environment:
      - DB_TYPE=POSTGRESQL
      - DB_USER=aurcache
      - DB_PWD=...
      - DB_HOST=dbhost
      - MAX_CONCURRENT_BUILDS=2
      - AUTO_UPDATE_SCHEDULE=0 */15 * * * *
      - LOG_LEVEL=DEBUG
      - CPU_LIMIT=100
      - MEMORY_LIMIT=10000
      - OAUTH_AUTH_URI=https://sso.heili.eu/application/o/authorize/
      - OAUTH_TOKEN_URI=https://sso.heili.eu/application/o/token/
      - OAUTH_CLIENT_ID=...
      - OAUTH_CLIENT_SECRET=...
      - OAUTH_REDIRECT_URI=https://aurcache.heili.eu/api/auth
      - OAUTH_USERINFO_URI=https://sso.heili.eu/application/o/userinfo/
    networks:
      aurcache_network:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8G
    labels:
      kuma.mygroup.group.name: 'aurcachegroup'

      kuma.mymonitor.http.name: 'AurCache Monitor'
      kuma.mymonitor.http.parent_name: 'mygroup'
      kuma.mymonitor.http.url: 'https://aurcache.heili.eu'

  aurcache_database:
    <<: *base
    image: postgres:17.4@sha256:81f32a88ec561664634637dd446487efd5f9d90996304b96210078e90e5c8b21
    volumes:
      - ${STORAGE_DATA_DIR}/aurcache/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=...
      - POSTGRES_USER=aurcache
    networks:
      aurcache_network:
        aliases:
          - "dbhost"

volumes:
  artifact_cache:
    driver: local

networks:
  aurcache_network:
    driver: bridge
```

I think your redirect url is wrong.
Not sure if i've documented this somewhere, maybe i should add this to the docs^^
