### ISSUE TITLE
BUG: Failed to acquire connection from pool: Connection pool timed out

### ISSUE THREAD

**Issue by fengwang** [Lukas-Heiligenbrunner/AURCache#27]
After creating docker container, I tried yay and yay-bin, both encountered `Failed to acquire connection from pool: Connection pool timed out` error.

The docker-compose.yml:

```yml
version: '3'
services:
    aurcache:
        image: ghcr.io/lukas-heiligenbrunner/aurcache:latest
        ports:
        - "10055:8080" # for pacman.conf
        - "10056:8081" # for UI
        volumes:
          - /data/docker/containers/aur-builder/data/db:/app/db
          - /data/docker/containers/aur-builder/data/repo:/app/repo
        privileged: true
        restart: unless-stopped
```

docker log:

[log.txt](https://github.com/user-attachments/files/16401206/log.txt)

the mapped volumes:

```
tree -L 4 /data/docker/containers/aur-builder/data
/data/docker/containers/aur-builder/data
├── db
│   └── db.sqlite
└── repo

3 directories, 1 file
```

**Comment by kodxana** [comment]
Same issues for any package I build

**Comment by Lukas-Heiligenbrunner** [comment]
Unfortunately I saw this bug some minutes after pushing the release. sorry for that. v0.1.1 is published now and you can update and it should work for sqlite and postgresql!

**Comment by kodxana** [comment]
@Lukas-Heiligenbrunner works fine tested with postgres
```
version: '3'
services:
  aurcache:
    image: ghcr.io/lukas-heiligenbrunner/aurcache:latest
    ports:
      - "8044:8080"
      - "8045:8081"
    volumes:
      - ./aurcache/repo:/app/repo
    privileged: true
    environment:
      - DB_TYPE=POSTGRESQL
      - DB_USER=aurcache_user
      - DB_PWD=
      - DB_HOST=aurcache-db
    depends_on:
      - aurcache-db

  aurcache-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: aurcache_user
      POSTGRES_PASSWORD: 
      POSTGRES_DB: aurcache
    volumes:
      - ./aurcache_db_data:/var/lib/postgresql/data
```
