### ISSUE TITLE
`Err` value: File exists (os error 17) 

### ISSUE THREAD

**Issue by CupricReki** [Lukas-Heiligenbrunner/AURCache#61]
docker container v0.1.3 and git fail to start. Tried v0.1.2 and it started file. 

```
aurcache-1  |               _    _ _____   _____           _
aurcache-1  |          /\  | |  | |  __ \ / ____|         | |
aurcache-1  |         /  \ | |  | | |__) | |     __ _  ___| |__   ___
aurcache-1  |        / /\ \| |  | |  _  /| |    / _` |/ __| '_ \ / _ \
aurcache-1  |       / ____ \ |__| | | \ \| |___| (_| | (__| | | |  __/
aurcache-1  |      /_/    \_\____/|_|  \_\\_____\__,_|\___|_| |_|\___|
aurcache-1  |
aurcache-1  | [2024-08-30T10:47:37Z INFO  sea_orm_migration::migrator] Applying all pending migrations
aurcache-1  | [2024-08-30T10:47:37Z INFO  sea_orm_migration::migrator] Applying migration 'create'
aurcache-1  | [2024-08-30T10:47:37Z INFO  sea_orm_migration::migrator] Migration 'create' has been applied
aurcache-1  | [2024-08-30T10:47:37Z INFO  pacman_repo_utils::repo_init] Initializing empty pacman Repo archive
aurcache-1  | thread 'main' panicked at src/main.rs:40:68:
aurcache-1  | called `Result::unwrap()` on an `Err` value: File exists (os error 17)
aurcache-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

docker-compose
```
services:
  aurcache:
    image: ghcr.io/lukas-heiligenbrunner/aurcache:latest
    ports:
      - "8044:8080"
      - "8045:8081"
    volumes:
      - ./aurcache/repo:/app/repo
    privileged: true
    environment:
      - DB_TYPE=POSTGRESQL
      - DB_USER=aurcache_user
      - DB_PWD=$DB_PWD
      - DB_HOST=aurcache-db
    depends_on:
      - aurcache-db

  aurcache-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: aurcache_user
      POSTGRES_PASSWORD: $DB_PWD
      POSTGRES_DB: aurcache
    volumes:
      - ./aurcache_db_data:/var/lib/postgresql/data
```
