### ISSUE TITLE
All package builds failing due to 'invalid gzip header'

### ISSUE THREAD

**Issue by CupricReki** [Lukas-Heiligenbrunner/AURCache#63]
Attached log

```
:: Proceed with installation? [Y/n]
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
installing flutter-engine-web-google-bin...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
flutter-3.24.1-1 (flutter-target-web flutter-intellij-patch flutter): parsing pkg list...
flutter-3.24.1-1 (flutter-target-web flutter-intellij-patch flutter): parsing pkg list...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
installing flutter-target-web...
installing flutter-intellij-patch...
Optional dependencies for flutter-intellij-patch
android-studio
intellij-idea-community-edition
intellij-idea-ultimate-edition
installing flutter...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
Copy 18 files from build dir to repo
Deleting 0 old files
invalid gzip header
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
installing flutter-target-web...
installing flutter-intellij-patch...
Optional dependencies for flutter-intellij-patch
android-studio
intellij-idea-community-edition
intellij-idea-ultimate-edition
installing flutter...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
Copy 18 files from build dir to repo
Deleting 0 old files
invalid gzip header
```

[aurcache_error.txt](https://github.com/user-attachments/files/16823234/aurcache_error.txt)

**Comment by vwidmer** [comment]
Can confirm I am having the same issue with any package I try

**Comment by Lukas-Heiligenbrunner** [comment]
Can you please upload your repo.db.tar.gz and repo.files.tar.gz files here? 
And did you try to delete the repo folder (and repo.db.tar.gz and repo.files.tar.gz) and restart the container?

**Comment by CupricReki** [comment]
See attached. Also noticed a bad symlink. I'll delete those files and restart. 

![image](https://github.com/user-attachments/assets/7ec44dcf-b09b-4a29-b237-55f849543856)

[repo.db.tar.gz](https://github.com/user-attachments/files/16825448/repo.db.tar.gz)
[repo.files.tar.gz](https://github.com/user-attachments/files/16825449/repo.files.tar.gz)

**Comment by CupricReki** [comment]
Here is the relevant portion of the docker log when trying to install hicolor-icon-theme-git
[aurcache_docker.log](https://github.com/user-attachments/files/16825485/aurcache_docker.log)

**Comment by CupricReki** [comment]
I just tried purging everything and starting clean. Same issue. Docker compose file:
```
services:
  aurcache:
    image: ghcr.io/lukas-heiligenbrunner/aurcache:latest
    container_name: aurcache
    ports:
      - "8044:8080"
      - "8045:8081"
    volumes:
      - ./aurcache/repo:/app/repo
    privileged: true
    environment:
      - DB_TYPE=POSTGRESQL
      - DB_USER=aurcache_user
      - DB_PWD=$DB_PWD
      - DB_HOST=aurcache-db
      - JOB_TIMEOUT=3600  # Timeout in (s) - 1 hour
      - LOG_LEVEL=debug
    depends_on:
      - aurcache-db
    restart: unless-stopped

  aurcache-db:
    image: postgres:latest
    container_name: aurcache-db
    environment:
      POSTGRES_USER: aurcache_user
      POSTGRES_PASSWORD: $DB_PWD
      POSTGRES_DB: aurcache
    volumes:
      - ./aurcache_db_data:/var/lib/postgresql/data
    restart: unless-stopped
```
