### ISSUE TITLE
Issue with Appimage packages

### ISSUE THREAD

**Issue by vwidmer** [Lukas-Heiligenbrunner/AURCache#69]
Seems to fail with any package I tried with appimages? 

`==> Validating source_x86_64 files with sha256sums...
    obsidian-bin-1.6.7-x86_64.AppImage ... 
Passed
==> Making package: obsidian-bin 1.6.7-1 (Sun Sep  1 12:34:12 2024)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found obsidian-bin-1.6.7-x86_64.AppImage
==> Validating source_x86_64 files with sha256sums...
    obsidian-bin-1.6.7-x86_64.AppImage ... 
Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
==> Starting prepare()...
/var/ab/.cache/paru/clone/obsidian-bin/PKGBUILD: line 28: ./obsidian-bin-1.6.7-x86_64.AppImage: cannot execute: required file not found
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'obsidian-bin-1.6.7-1': 
error: packages failed to build: obsidian-bin-1.6.7-1
No files found in build directory`

and

`==> Validating source_x86_64 files with sha256sums...
    via-3.0.0-linux.AppImage ... 
Passed
==> Making package: via-appimage 3.0.0-1 (Mon Sep  2 10:58:39 2024)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found via-3.0.0-linux.AppImage
==> Validating source_x86_64 files with sha256sums...
    via-3.0.0-linux.AppImage ... 
Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
==> Starting prepare()...
/var/ab/.cache/paru/clone/via-appimage/PKGBUILD: line 24: ./via-3.0.0-linux.AppImage: cannot execute: required file not found
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'via-appimage-3.0.0-1': 
error: packages failed to build: via-appimage-3.0.0-1
No files found in build directory`

Let me know what else I can provide to help

**Comment by Lukas-Heiligenbrunner** [comment]
Might be a FUSE problem? https://itsfoss.com/cant-run-appimage-ubuntu/

Did you enable fuse when running docker in an lxc container? 🤔

**Comment by vwidmer** [comment]
It is running on Manjaro I have no problem installing the packages directly on the system. 

This is my compose file I have both

```
devices:
      - /dev/fuse:/dev/fuse
    privileged: true
```
    
```
 version: "3"
services:
  aurcache:
    image: ghcr.io/lukas-heiligenbrunner/aurcache:latest
    ports:
      - 9080:8080
      - 9081:8081
    volumes:
      - /docker/aurcache/db:/app/db
      - /docker/aurcache/repo:/app/repo
    devices:
      - /dev/fuse:/dev/fuse
    privileged: true
networks: {}
```
 in it am I missing something else?
